create table
    rule
(
    id         text primary key not null,
    name       text             not null,
    sort_order integer          not null
);

create table
    question
(
    id              bigint primary key generated by default as identity,
    text            text    not null,
    rule_id         text references rule (id),
    question_number integer not null,
    tsv             tsvector,
    constraint uni_rule_question_number
        unique (rule_id, question_number)
);

create table
    choice
(
    id          bigint primary key generated by default as identity,
    question_id bigint references question (id),
    option      text    not null,
    text        text    not null,
    is_answer   boolean not null
);

create table
    reference
(
    id          bigint primary key generated by default as identity,
    question_id bigint references question (id),
    text        text not null
);

create table
    feedback
(
    id       bigint primary key generated by default as identity,
    email    text not null,
    name     text not null,
    topic    text not null,
    text text not null,
    is_acknowledged  boolean default false,
    is_completed     boolean default false
);

create table
    quiz_config
(
    id       bigint primary key generated by default as identity,
    key text not null unique ,
    num_questions integer,
    duration_in_minutes integer,
    has_negative_marking boolean
);

create table quiz_config_rules (
    id bigint primary key generated by default as identity,
    quiz_config_id bigint references quiz_config (id),
    rule_id text references rule (id)
);

UPDATE question
SET tsv = setweight(to_tsvector(text), 'A');
CREATE INDEX idx_question_tsv ON question USING GIN (tsv);