create table
    rule
(

    id         text primary key not null,
    name       text             not null,
    sort_order integer          not null
);

create table
    question
(
    id              bigint primary key generated by default as identity,
    text            text    not null,
    rule_id            text references rule (id),
    question_number integer not null
);

create table
    choice
(
    id          bigint primary key generated by default as identity,
    question_id bigint references question (id),
    option      text    not null,
    text        text    not null,
    is_answer   boolean not null
);

create table
    reference
(
    id          bigint primary key generated by default as identity,
    question_id bigint references question (id),
    text        text not null
);

ALTER TABLE question ADD COLUMN tsv tsvector;
UPDATE question SET tsv = setweight(to_tsvector(text), 'A');
CREATE INDEX idx_question_tsv ON question USING GIN(tsv);